
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action OpenPolicyAction;
	
	private global::Gtk.Action SavePolicyAction;
	
	private global::Gtk.Action QuitAction;
	
	private global::Gtk.VBox vbox0;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.VBox vbox;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Entry grid_size_rows;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Entry grid_size_cols;
	
	private global::Gtk.Alignment alignment3;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.RadioButton rdo_sim_drones;
	
	private global::Gtk.RadioButton rdo_phys_drones;
	
	private global::Gtk.Alignment alignment9;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.ComboBox cbo_scenario;
	
	private global::Gtk.Alignment alignment8;
	
	private global::Gtk.Entry num_decisions;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Frame frame_fugitive_settings;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.VBox box_scenariosettings;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Entry safe_house_row;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Entry safe_house_col;
	
	private global::Gtk.Alignment alignment4;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.Label label13;
	
	private global::Gtk.Entry max_moves;
	
	private global::Gtk.Alignment alignment10;
	
	private global::Gtk.Frame frame2;
	
	private global::Gtk.Alignment GtkAlignment1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.ComboBox cbo_fug_mode;
	
	private global::Gtk.FileChooserButton filechsr_fugitive;
	
	private global::Gtk.Entry fug_row;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Entry fug_col;
	
	private global::Gtk.Alignment alignment5;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.ComboBox cbo_uav1_mode;
	
	private global::Gtk.FileChooserButton filechsr_uav1;
	
	private global::Gtk.Entry uav1_row;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Entry uav1_col;
	
	private global::Gtk.Alignment alignment6;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.ComboBox cbo_uav2_mode;
	
	private global::Gtk.FileChooserButton filechsr_uav2;
	
	private global::Gtk.Entry uav2_row;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.Entry uav2_col;
	
	private global::Gtk.Alignment alignment7;
	
	private global::Gtk.Label GtkLabel6;
	
	private global::Gtk.Label GtkLabel7;
	
	private global::Gtk.Frame frame_coord_settings;
	
	private global::Gtk.Alignment GtkAlignment2;
	
	private global::Gtk.VBox box_scenariosettings1;
	
	private global::Gtk.Frame frame4;
	
	private global::Gtk.Alignment GtkAlignment3;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox13;
	
	private global::Gtk.Label label19;
	
	private global::Gtk.ComboBox cbo_coord_uav1_mode;
	
	private global::Gtk.FileChooserButton filechsr_coord_uav1;
	
	private global::Gtk.Entry coord_uav1_row;
	
	private global::Gtk.Label label20;
	
	private global::Gtk.Entry coord_uav1_col;
	
	private global::Gtk.Alignment alignment14;
	
	private global::Gtk.HBox hbox14;
	
	private global::Gtk.Label label21;
	
	private global::Gtk.ComboBox cbo_coord_uav2_mode;
	
	private global::Gtk.FileChooserButton filechsr_coord_uav2;
	
	private global::Gtk.Entry coord_uav2_row;
	
	private global::Gtk.Label label22;
	
	private global::Gtk.Entry coord_uav2_col;
	
	private global::Gtk.Alignment alignment15;
	
	private global::Gtk.Label GtkLabel12;
	
	private global::Gtk.Label GtkLabel13;
	
	private global::Gtk.Alignment alignment1;
	
	private global::Gtk.Image image1;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Alignment alignment2;
	
	private global::Gtk.Button btn_launch;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.Fixed PolicyArea;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileAction, "<Alt><Mod2>o");
		this.OpenPolicyAction = new global::Gtk.Action ("OpenPolicyAction", global::Mono.Unix.Catalog.GetString ("_Open Policy"), null, null);
		this.OpenPolicyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open Policy");
		w1.Add (this.OpenPolicyAction, "<Alt><Mod2>o");
		this.SavePolicyAction = new global::Gtk.Action ("SavePolicyAction", global::Mono.Unix.Catalog.GetString ("_Save Policy"), null, null);
		this.SavePolicyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save Policy");
		w1.Add (this.SavePolicyAction, "<Alt><Mod2>q");
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.QuitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("GaTAC Launcher");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox0 = new global::Gtk.VBox ();
		this.vbox0.Name = "vbox0";
		this.vbox0.Spacing = 6;
		// Container child vbox0.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='OpenPolicyAction' action='OpenPolicyAction'/><menuitem name='SavePolicyAction' action='SavePolicyAction'/><menuitem name='QuitAction' action='QuitAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox0.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox0 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox0.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 386;
		this.hpaned1.BorderWidth = ((uint)(3));
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox = new global::Gtk.VBox ();
		this.vbox.Name = "vbox";
		this.vbox.Spacing = 6;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Grid Size");
		this.hbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.grid_size_rows = new global::Gtk.Entry ();
		this.grid_size_rows.CanFocus = true;
		this.grid_size_rows.Name = "grid_size_rows";
		this.grid_size_rows.IsEditable = true;
		this.grid_size_rows.WidthChars = 2;
		this.grid_size_rows.MaxLength = 2;
		this.grid_size_rows.InvisibleChar = '●';
		this.hbox1.Add (this.grid_size_rows);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.grid_size_rows]));
		w4.Position = 1;
		w4.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("X");
		this.hbox1.Add (this.label2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label2]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.grid_size_cols = new global::Gtk.Entry ();
		this.grid_size_cols.CanFocus = true;
		this.grid_size_cols.Name = "grid_size_cols";
		this.grid_size_cols.IsEditable = true;
		this.grid_size_cols.WidthChars = 2;
		this.grid_size_cols.MaxLength = 2;
		this.grid_size_cols.InvisibleChar = '●';
		this.hbox1.Add (this.grid_size_cols);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.grid_size_cols]));
		w6.Position = 3;
		w6.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		this.hbox1.Add (this.alignment3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment3]));
		w7.Position = 4;
		this.vbox.Add (this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox1]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.rdo_sim_drones = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Simulated Drones"));
		this.rdo_sim_drones.CanFocus = true;
		this.rdo_sim_drones.Name = "rdo_sim_drones";
		this.rdo_sim_drones.DrawIndicator = true;
		this.rdo_sim_drones.UseUnderline = true;
		this.rdo_sim_drones.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox8.Add (this.rdo_sim_drones);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.rdo_sim_drones]));
		w9.Position = 0;
		w9.Expand = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.rdo_phys_drones = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Physical Drones"));
		this.rdo_phys_drones.CanFocus = true;
		this.rdo_phys_drones.Name = "rdo_phys_drones";
		this.rdo_phys_drones.DrawIndicator = true;
		this.rdo_phys_drones.UseUnderline = true;
		this.rdo_phys_drones.Group = this.rdo_sim_drones.Group;
		this.hbox8.Add (this.rdo_phys_drones);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.rdo_phys_drones]));
		w10.Position = 1;
		w10.Expand = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment9.Name = "alignment9";
		this.hbox8.Add (this.alignment9);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment9]));
		w11.Position = 2;
		this.vbox.Add (this.hbox8);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox8]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Scenario");
		this.hbox2.Add (this.label3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.cbo_scenario = global::Gtk.ComboBox.NewText ();
		this.cbo_scenario.AppendText (global::Mono.Unix.Catalog.GetString ("Fugitive"));
		this.cbo_scenario.AppendText (global::Mono.Unix.Catalog.GetString ("Anti-Coordination"));
		this.cbo_scenario.AppendText (global::Mono.Unix.Catalog.GetString ("Coordination"));
		this.cbo_scenario.Name = "cbo_scenario";
		this.cbo_scenario.Active = 0;
		this.hbox2.Add (this.cbo_scenario);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cbo_scenario]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment8.Name = "alignment8";
		this.hbox2.Add (this.alignment8);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment8]));
		w15.PackType = ((global::Gtk.PackType)(1));
		w15.Position = 2;
		// Container child hbox2.Gtk.Box+BoxChild
		this.num_decisions = new global::Gtk.Entry ();
		this.num_decisions.CanFocus = true;
		this.num_decisions.Name = "num_decisions";
		this.num_decisions.Text = global::Mono.Unix.Catalog.GetString ("4");
		this.num_decisions.IsEditable = true;
		this.num_decisions.WidthChars = 3;
		this.num_decisions.MaxLength = 3;
		this.num_decisions.InvisibleChar = '●';
		this.hbox2.Add (this.num_decisions);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.num_decisions]));
		w16.PackType = ((global::Gtk.PackType)(1));
		w16.Position = 3;
		w16.Expand = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Decisions");
		this.hbox2.Add (this.label6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label6]));
		w17.PackType = ((global::Gtk.PackType)(1));
		w17.Position = 4;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox.Add (this.hbox2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox2]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.frame_fugitive_settings = new global::Gtk.Frame ();
		this.frame_fugitive_settings.Name = "frame_fugitive_settings";
		this.frame_fugitive_settings.BorderWidth = ((uint)(1));
		// Container child frame_fugitive_settings.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.box_scenariosettings = new global::Gtk.VBox ();
		this.box_scenariosettings.Name = "box_scenariosettings";
		this.box_scenariosettings.Spacing = 6;
		// Container child box_scenariosettings.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Safe House Pos");
		this.hbox3.Add (this.label4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label4]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.safe_house_row = new global::Gtk.Entry ();
		this.safe_house_row.CanFocus = true;
		this.safe_house_row.Name = "safe_house_row";
		this.safe_house_row.IsEditable = true;
		this.safe_house_row.WidthChars = 2;
		this.safe_house_row.MaxLength = 2;
		this.safe_house_row.InvisibleChar = '●';
		this.hbox3.Add (this.safe_house_row);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.safe_house_row]));
		w20.Position = 1;
		w20.Expand = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("X");
		this.hbox3.Add (this.label5);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label5]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.safe_house_col = new global::Gtk.Entry ();
		this.safe_house_col.CanFocus = true;
		this.safe_house_col.Name = "safe_house_col";
		this.safe_house_col.IsEditable = true;
		this.safe_house_col.WidthChars = 2;
		this.safe_house_col.MaxLength = 2;
		this.safe_house_col.InvisibleChar = '●';
		this.hbox3.Add (this.safe_house_col);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.safe_house_col]));
		w22.Position = 3;
		w22.Expand = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment4.Name = "alignment4";
		this.hbox3.Add (this.alignment4);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment4]));
		w23.Position = 4;
		this.box_scenariosettings.Add (this.hbox3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.box_scenariosettings [this.hbox3]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child box_scenariosettings.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Max Moves");
		this.hbox9.Add (this.label13);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label13]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.max_moves = new global::Gtk.Entry ();
		this.max_moves.CanFocus = true;
		this.max_moves.Name = "max_moves";
		this.max_moves.IsEditable = true;
		this.max_moves.WidthChars = 3;
		this.max_moves.MaxLength = 3;
		this.max_moves.InvisibleChar = '●';
		this.hbox9.Add (this.max_moves);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.max_moves]));
		w26.Position = 1;
		w26.Expand = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.alignment10 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment10.Name = "alignment10";
		this.hbox9.Add (this.alignment10);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment10]));
		w27.Position = 2;
		this.box_scenariosettings.Add (this.hbox9);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.box_scenariosettings [this.hbox9]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		// Container child box_scenariosettings.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.BorderWidth = ((uint)(1));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Fugitive");
		this.hbox4.Add (this.label8);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label8]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.cbo_fug_mode = global::Gtk.ComboBox.NewText ();
		this.cbo_fug_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Policy File"));
		this.cbo_fug_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Editor Policy"));
		this.cbo_fug_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Random"));
		this.cbo_fug_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Keyboard"));
		this.cbo_fug_mode.Name = "cbo_fug_mode";
		this.hbox4.Add (this.cbo_fug_mode);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.cbo_fug_mode]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.filechsr_fugitive = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechsr_fugitive.Name = "filechsr_fugitive";
		this.hbox4.Add (this.filechsr_fugitive);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.filechsr_fugitive]));
		w31.Position = 2;
		// Container child hbox4.Gtk.Box+BoxChild
		this.fug_row = new global::Gtk.Entry ();
		this.fug_row.CanFocus = true;
		this.fug_row.Name = "fug_row";
		this.fug_row.IsEditable = true;
		this.fug_row.WidthChars = 2;
		this.fug_row.MaxLength = 2;
		this.fug_row.InvisibleChar = '●';
		this.hbox4.Add (this.fug_row);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fug_row]));
		w32.Position = 3;
		w32.Expand = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("X");
		this.hbox4.Add (this.label7);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label7]));
		w33.Position = 4;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.fug_col = new global::Gtk.Entry ();
		this.fug_col.CanFocus = true;
		this.fug_col.Name = "fug_col";
		this.fug_col.IsEditable = true;
		this.fug_col.WidthChars = 2;
		this.fug_col.MaxLength = 2;
		this.fug_col.InvisibleChar = '●';
		this.hbox4.Add (this.fug_col);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fug_col]));
		w34.Position = 5;
		w34.Expand = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment5.Name = "alignment5";
		this.hbox4.Add (this.alignment5);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment5]));
		w35.Position = 6;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("UAV 1");
		this.hbox5.Add (this.label10);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label10]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.cbo_uav1_mode = global::Gtk.ComboBox.NewText ();
		this.cbo_uav1_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Policy File"));
		this.cbo_uav1_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Editor Policy"));
		this.cbo_uav1_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Random"));
		this.cbo_uav1_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Keyboard"));
		this.cbo_uav1_mode.Name = "cbo_uav1_mode";
		this.hbox5.Add (this.cbo_uav1_mode);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.cbo_uav1_mode]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.filechsr_uav1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechsr_uav1.Name = "filechsr_uav1";
		this.hbox5.Add (this.filechsr_uav1);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.filechsr_uav1]));
		w39.Position = 2;
		// Container child hbox5.Gtk.Box+BoxChild
		this.uav1_row = new global::Gtk.Entry ();
		this.uav1_row.CanFocus = true;
		this.uav1_row.Name = "uav1_row";
		this.uav1_row.IsEditable = true;
		this.uav1_row.WidthChars = 2;
		this.uav1_row.MaxLength = 2;
		this.uav1_row.InvisibleChar = '●';
		this.hbox5.Add (this.uav1_row);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.uav1_row]));
		w40.Position = 3;
		w40.Expand = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("X");
		this.hbox5.Add (this.label9);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label9]));
		w41.Position = 4;
		w41.Expand = false;
		w41.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.uav1_col = new global::Gtk.Entry ();
		this.uav1_col.CanFocus = true;
		this.uav1_col.Name = "uav1_col";
		this.uav1_col.IsEditable = true;
		this.uav1_col.WidthChars = 2;
		this.uav1_col.MaxLength = 2;
		this.uav1_col.InvisibleChar = '●';
		this.hbox5.Add (this.uav1_col);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.uav1_col]));
		w42.Position = 5;
		w42.Expand = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment6.Name = "alignment6";
		this.hbox5.Add (this.alignment6);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.alignment6]));
		w43.Position = 6;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w44.Position = 1;
		w44.Expand = false;
		w44.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("UAV 2");
		this.hbox6.Add (this.label12);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label12]));
		w45.Position = 0;
		w45.Expand = false;
		w45.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.cbo_uav2_mode = global::Gtk.ComboBox.NewText ();
		this.cbo_uav2_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Policy File"));
		this.cbo_uav2_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Editor Policy"));
		this.cbo_uav2_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Random"));
		this.cbo_uav2_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Keyboard"));
		this.cbo_uav2_mode.Name = "cbo_uav2_mode";
		this.hbox6.Add (this.cbo_uav2_mode);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.cbo_uav2_mode]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.filechsr_uav2 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechsr_uav2.Name = "filechsr_uav2";
		this.hbox6.Add (this.filechsr_uav2);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.filechsr_uav2]));
		w47.Position = 2;
		// Container child hbox6.Gtk.Box+BoxChild
		this.uav2_row = new global::Gtk.Entry ();
		this.uav2_row.CanFocus = true;
		this.uav2_row.Name = "uav2_row";
		this.uav2_row.IsEditable = true;
		this.uav2_row.WidthChars = 2;
		this.uav2_row.MaxLength = 2;
		this.uav2_row.InvisibleChar = '●';
		this.hbox6.Add (this.uav2_row);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.uav2_row]));
		w48.Position = 3;
		w48.Expand = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("X");
		this.hbox6.Add (this.label11);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label11]));
		w49.Position = 4;
		w49.Expand = false;
		w49.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.uav2_col = new global::Gtk.Entry ();
		this.uav2_col.CanFocus = true;
		this.uav2_col.Name = "uav2_col";
		this.uav2_col.IsEditable = true;
		this.uav2_col.WidthChars = 2;
		this.uav2_col.MaxLength = 2;
		this.uav2_col.InvisibleChar = '●';
		this.hbox6.Add (this.uav2_col);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.uav2_col]));
		w50.Position = 5;
		w50.Expand = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment7.Name = "alignment7";
		this.hbox6.Add (this.alignment7);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.alignment7]));
		w51.Position = 6;
		this.vbox2.Add (this.hbox6);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
		w52.Position = 2;
		w52.Expand = false;
		w52.Fill = false;
		this.GtkAlignment1.Add (this.vbox2);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel6 = new global::Gtk.Label ();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Control and Start Positions</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel6;
		this.box_scenariosettings.Add (this.frame2);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.box_scenariosettings [this.frame2]));
		w55.Position = 2;
		w55.Expand = false;
		w55.Fill = false;
		this.GtkAlignment.Add (this.box_scenariosettings);
		this.frame_fugitive_settings.Add (this.GtkAlignment);
		this.GtkLabel7 = new global::Gtk.Label ();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Scenario Settings</b>");
		this.GtkLabel7.UseMarkup = true;
		this.frame_fugitive_settings.LabelWidget = this.GtkLabel7;
		this.vbox.Add (this.frame_fugitive_settings);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox [this.frame_fugitive_settings]));
		w58.Position = 3;
		w58.Expand = false;
		w58.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.frame_coord_settings = new global::Gtk.Frame ();
		this.frame_coord_settings.Name = "frame_coord_settings";
		this.frame_coord_settings.BorderWidth = ((uint)(1));
		// Container child frame_coord_settings.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.box_scenariosettings1 = new global::Gtk.VBox ();
		this.box_scenariosettings1.Name = "box_scenariosettings1";
		this.box_scenariosettings1.Spacing = 6;
		// Container child box_scenariosettings1.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.BorderWidth = ((uint)(1));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label ();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("UAV 1");
		this.hbox13.Add (this.label19);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label19]));
		w59.Position = 0;
		w59.Expand = false;
		w59.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.cbo_coord_uav1_mode = global::Gtk.ComboBox.NewText ();
		this.cbo_coord_uav1_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Policy File"));
		this.cbo_coord_uav1_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Editor Policy"));
		this.cbo_coord_uav1_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Keyboard"));
		this.cbo_coord_uav1_mode.Name = "cbo_coord_uav1_mode";
		this.hbox13.Add (this.cbo_coord_uav1_mode);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.cbo_coord_uav1_mode]));
		w60.Position = 1;
		w60.Expand = false;
		w60.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.filechsr_coord_uav1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechsr_coord_uav1.Name = "filechsr_coord_uav1";
		this.hbox13.Add (this.filechsr_coord_uav1);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.filechsr_coord_uav1]));
		w61.Position = 2;
		// Container child hbox13.Gtk.Box+BoxChild
		this.coord_uav1_row = new global::Gtk.Entry ();
		this.coord_uav1_row.CanFocus = true;
		this.coord_uav1_row.Name = "coord_uav1_row";
		this.coord_uav1_row.IsEditable = true;
		this.coord_uav1_row.WidthChars = 2;
		this.coord_uav1_row.MaxLength = 2;
		this.coord_uav1_row.InvisibleChar = '●';
		this.hbox13.Add (this.coord_uav1_row);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.coord_uav1_row]));
		w62.Position = 3;
		w62.Expand = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label20 = new global::Gtk.Label ();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("X");
		this.hbox13.Add (this.label20);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label20]));
		w63.Position = 4;
		w63.Expand = false;
		w63.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.coord_uav1_col = new global::Gtk.Entry ();
		this.coord_uav1_col.CanFocus = true;
		this.coord_uav1_col.Name = "coord_uav1_col";
		this.coord_uav1_col.IsEditable = true;
		this.coord_uav1_col.WidthChars = 2;
		this.coord_uav1_col.MaxLength = 2;
		this.coord_uav1_col.InvisibleChar = '●';
		this.hbox13.Add (this.coord_uav1_col);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.coord_uav1_col]));
		w64.Position = 5;
		w64.Expand = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.alignment14 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment14.Name = "alignment14";
		this.hbox13.Add (this.alignment14);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.alignment14]));
		w65.Position = 6;
		this.vbox3.Add (this.hbox13);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox13]));
		w66.Position = 1;
		w66.Expand = false;
		w66.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label21 = new global::Gtk.Label ();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("UAV 2");
		this.hbox14.Add (this.label21);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label21]));
		w67.Position = 0;
		w67.Expand = false;
		w67.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.cbo_coord_uav2_mode = global::Gtk.ComboBox.NewText ();
		this.cbo_coord_uav2_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Policy File"));
		this.cbo_coord_uav2_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Editor Policy"));
		this.cbo_coord_uav2_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Keyboard"));
		this.cbo_coord_uav2_mode.Name = "cbo_coord_uav2_mode";
		this.hbox14.Add (this.cbo_coord_uav2_mode);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.cbo_coord_uav2_mode]));
		w68.Position = 1;
		w68.Expand = false;
		w68.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.filechsr_coord_uav2 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechsr_coord_uav2.Name = "filechsr_coord_uav2";
		this.hbox14.Add (this.filechsr_coord_uav2);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.filechsr_coord_uav2]));
		w69.Position = 2;
		// Container child hbox14.Gtk.Box+BoxChild
		this.coord_uav2_row = new global::Gtk.Entry ();
		this.coord_uav2_row.CanFocus = true;
		this.coord_uav2_row.Name = "coord_uav2_row";
		this.coord_uav2_row.IsEditable = true;
		this.coord_uav2_row.WidthChars = 2;
		this.coord_uav2_row.MaxLength = 2;
		this.coord_uav2_row.InvisibleChar = '●';
		this.hbox14.Add (this.coord_uav2_row);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.coord_uav2_row]));
		w70.Position = 3;
		w70.Expand = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label22 = new global::Gtk.Label ();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("X");
		this.hbox14.Add (this.label22);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label22]));
		w71.Position = 4;
		w71.Expand = false;
		w71.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.coord_uav2_col = new global::Gtk.Entry ();
		this.coord_uav2_col.CanFocus = true;
		this.coord_uav2_col.Name = "coord_uav2_col";
		this.coord_uav2_col.IsEditable = true;
		this.coord_uav2_col.WidthChars = 2;
		this.coord_uav2_col.MaxLength = 2;
		this.coord_uav2_col.InvisibleChar = '●';
		this.hbox14.Add (this.coord_uav2_col);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.coord_uav2_col]));
		w72.Position = 5;
		w72.Expand = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.alignment15 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment15.Name = "alignment15";
		this.hbox14.Add (this.alignment15);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.alignment15]));
		w73.Position = 6;
		this.vbox3.Add (this.hbox14);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox14]));
		w74.Position = 2;
		w74.Expand = false;
		w74.Fill = false;
		this.GtkAlignment3.Add (this.vbox3);
		this.frame4.Add (this.GtkAlignment3);
		this.GtkLabel12 = new global::Gtk.Label ();
		this.GtkLabel12.Name = "GtkLabel12";
		this.GtkLabel12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Control and Start Positions</b>");
		this.GtkLabel12.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel12;
		this.box_scenariosettings1.Add (this.frame4);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.box_scenariosettings1 [this.frame4]));
		w77.Position = 2;
		this.GtkAlignment2.Add (this.box_scenariosettings1);
		this.frame_coord_settings.Add (this.GtkAlignment2);
		this.GtkLabel13 = new global::Gtk.Label ();
		this.GtkLabel13.Name = "GtkLabel13";
		this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Scenario Settings</b>");
		this.GtkLabel13.UseMarkup = true;
		this.frame_coord_settings.LabelWidget = this.GtkLabel13;
		this.vbox.Add (this.frame_coord_settings);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.vbox [this.frame_coord_settings]));
		w80.Position = 4;
		// Container child vbox.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.image1.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "../../GaTAC_logo.png"));
		this.alignment1.Add (this.image1);
		this.vbox.Add (this.alignment1);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox [this.alignment1]));
		w82.Position = 5;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.hbox7.Add (this.alignment2);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.alignment2]));
		w83.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.btn_launch = new global::Gtk.Button ();
		this.btn_launch.CanFocus = true;
		this.btn_launch.Name = "btn_launch";
		this.btn_launch.UseUnderline = true;
		this.btn_launch.Label = global::Mono.Unix.Catalog.GetString ("Launch");
		this.hbox7.Add (this.btn_launch);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.btn_launch]));
		w84.Position = 1;
		w84.Expand = false;
		w84.Fill = false;
		this.vbox.Add (this.hbox7);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox7]));
		w85.PackType = ((global::Gtk.PackType)(1));
		w85.Position = 6;
		w85.Expand = false;
		w85.Fill = false;
		this.hpaned1.Add (this.vbox);
		global::Gtk.Paned.PanedChild w86 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox]));
		w86.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w87 = new global::Gtk.Viewport ();
		w87.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.PolicyArea = new global::Gtk.Fixed ();
		this.PolicyArea.Name = "PolicyArea";
		this.PolicyArea.HasWindow = false;
		w87.Add (this.PolicyArea);
		this.GtkScrolledWindow.Add (w87);
		this.hpaned1.Add (this.GtkScrolledWindow);
		this.vbox0.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox0 [this.hpaned1]));
		w91.Position = 1;
		this.Add (this.vbox0);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1126;
		this.DefaultHeight = 774;
		this.filechsr_fugitive.Hide ();
		this.filechsr_uav1.Hide ();
		this.filechsr_uav2.Hide ();
		this.filechsr_coord_uav1.Hide ();
		this.filechsr_coord_uav2.Hide ();
		this.frame_coord_settings.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.OpenPolicyAction.Activated += new global::System.EventHandler (this.mnu_open);
		this.SavePolicyAction.Activated += new global::System.EventHandler (this.mnu_save);
		this.QuitAction.Activated += new global::System.EventHandler (this.on_quit);
		this.cbo_scenario.Changed += new global::System.EventHandler (this.change_scenario);
		this.num_decisions.Changed += new global::System.EventHandler (this.changed_decisions);
		this.cbo_fug_mode.Changed += new global::System.EventHandler (this.fugitive_control_changed);
		this.cbo_uav1_mode.Changed += new global::System.EventHandler (this.uav1_control_changed);
		this.cbo_uav2_mode.Changed += new global::System.EventHandler (this.uav2_control_changed);
		this.cbo_coord_uav1_mode.Changed += new global::System.EventHandler (this.coord_uav1_control_changed);
		this.cbo_coord_uav2_mode.Changed += new global::System.EventHandler (this.coord_uav2_control_changed);
		this.btn_launch.Clicked += new global::System.EventHandler (this.launch_button);
	}
}
